
; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:sparkfun_esp32s2_thing_plus_c]
platform = espressif32
board = sparkfun_esp32s2_thing_plus_c
framework = arduino
monitor_speed = 115200
lib_deps = milesburton/DallasTemperature@^4.0.6
    paulstoffregen/OneWire@^2.3.8
    adafruit/Adafruit seesaw Library@^1.7.9
    adafruit/Adafruit BME680 Library@^2.0.6
    boschsensortec/BSEC Software Library @ ^1.8.1492
    sandeepmistry/LoRa@^0.8.0
build_flags =
    -I".pio/libdeps/default/BSEC Software Library/src/inc"
    -L".pio/libdeps/default/BSEC Software Library/src/esp32"
    -lalgobsec
